'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Countdown.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to === Change Log ===
        '''
        '''Version 0.8              (Aug 10, 2016)
        '''    Minor documentation improvements
        '''    Added a Unique() extension method that extracts the unique permutations in a T()() array
        '''
        '''Version 0.7              (Apr 30, 2016)
        '''    Minor bug fixes
        '''    Several UI enhancements
        '''
        '''Version 0.6              (Dec 01, 2010)
        '''    Fixed bug with the way the program was handling the parenthesis in the equations
        '''    Added the command line parameter /w to pause the output when a solution is found
        '''
        '''Version [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property StrChangeLog() As String
            Get
                Return ResourceManager.GetString("StrChangeLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The input string must be of the form:
        '''TARGET:{VALUE};SOURCE:{LIST OF AT LEAST TWO REAL VALUES SEPARATED BY COMMAS}; [/sp] [/all] [/p:n] [/w] [/e]
        '''
        '''For example, these are valid input strings:
        '''TARGET:104;SOURCE:100,3,4,7,1,2;
        '''TARGET:5;SOURCE:1,2,3,5;
        '''
        '''TARGET:10;SOURCE:1,1,5,8;
        '''Will produce the following result: (8/(1-(1/5))) == 10
        '''
        ''' === Parameters ===
        '''
        '''/sp - Display the program&apos;s progress:
        '''countdown.exe TARGET:104;SOURCE:100,3,4,7,1,2; /sp
        '''
        '''/all - Have the program find all possible solutions:
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property StrDocumentation() As String
            Get
                Return ResourceManager.GetString("StrDocumentation", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
